name: Get Pzubslic IP

on:
  push:
    branches:
      - main

jobs:
  set-env:
    name: set-env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get SDK
        run: pip install huaweicloudsdkvpc
        
        
      - name: Run Python Script
        id: first_id
        run: |
          python script.py
          echo $SG_RULE_ID
          echo "sg_rule_id=${SG_RULE_ID}" >> $GITHUB_ENV
          echo $GITHUB_ENV
        env:
          CLOUD_SDK_AK: ${{ secrets.CLOUD_SDK_AK }}
          CLOUD_SDK_SK: ${{ secrets.CLOUD_SDK_SK }}

          
      - name: Run Python Script2
        run: |
          echo $SG_RULE_ID
          python script2.py
        env:
          CLOUD_SDK_AK: ${{ secrets.CLOUD_SDK_AK }}
          CLOUD_SDK_SK: ${{ secrets.CLOUD_SDK_SK }}
          SG_RULE_ID:  ${{ env.sg_rule_id }}
          
